logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    org.entando.bundle: DEBUG
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/case-management-bundle?useSSL=false&allowPublicKeyRetrieval=true
    username: case-management-bundle-user
    password: case-management-bundle-password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/entando-dev
        registration:
          oidc:
            client-id: internal
aws:
  s3:
    key: ${AWS_ACCESS_KEY_ID:my_access_key}
    secret: ${AWS_SECRET_ACCESS_KEY:my_secret_access_key}
    region: ${AWS_DEFAULT_REGION:eu-west-1}
    bucket:
      name: ${S3_BUCKET_NAME:entando-cdp-poc}